name: Initialize Template

# Only runs once when repository is created from template
on:
  push:
    branches: [main]

jobs:
  initialize:
    if: github.repository != 'cto4ai/docs-as-code-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Personalize repository
        run: |
          # Basic template variable replacement using repository information
          REPO_NAME="${{ github.event.repository.name }}"
          GITHUB_ORG="${{ github.repository_owner }}"

          # Replace template variables in key files
          find . -name "*.md" -o -name "*.json" -o -name "*.yml" | grep -v node_modules | xargs -I {} \
            sed -i.bak \
            -e "s/{{REPO_NAME}}/$REPO_NAME/g" \
            -e "s/{{GITHUB_ORG}}/$GITHUB_ORG/g" \
            -e "s/{{COMPANY_NAME}}/$(echo $REPO_NAME | sed 's/-/ /g' | sed 's/\b\w/\U&/g')/g" \
            -e "s/{{DOCS_EMAIL}}/docs@example.com/g" \
            -e "s/{{SLACK_CHANNEL}}/#docs-help/g" {}

          # Clean up backup files
          find . -name "*.bak" -delete

          # Remove example content
          rm -rf docs/examples

          # Remove template instructions
          rm -f TEMPLATE_INSTRUCTIONS.md

      - name: Create setup issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚀 Documentation Repository Ready!',
              body: `## Welcome to your personalized documentation repository!

              Your repository has been automatically configured with:
              - ✅ Template variables replaced with repository information
              - ✅ Example content removed
              - ✅ Dependencies installed

              ### Next Steps
              1. [ ] Configure branch protection rules in Settings → Branches
              2. [ ] Set up team permissions in Settings → Manage access
              3. [ ] Review and customize the README.md if needed
              4. [ ] Add your first documentation in the docs/ folder
              5. [ ] Set up GitHub Pages for publishing (optional)

              ### Getting Started
              - See [setup guide](.github/DOCUMENTATION/setup-guide.md) for detailed instructions
              - Use [document templates](./docs/templates/) for new content
              - Run \`npm run validate\` to check your documentation

              You can close this issue when you're ready to start documenting!`
            })
      
      - name: Commit personalized changes
        run: |
          # Delete this initialization workflow
          rm .github/workflows/init-template.yml

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Commit all changes
          git add -A
          git commit -m "Initialize documentation repository from template

- Replace template variables with repository information
- Remove example content and template instructions
- Set up basic configuration
- Remove initialization workflow"

          git push
